apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: smarthome
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort
